version: "3.9"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "bash", "-lc", "cub kafka-ready -b localhost:9092 1 20 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 6

  api:
    build:
      context: ../api
    container_name: api
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  connector:
    build:
      context: ../connector
    container_name: connector
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ACQUIRER_URL=http://acquirer:5000/process
    depends_on:
      - kafka
      - api
      - acquirer

  acquirer:
    build:
      context: ../acquirer_simulator
    container_name: acquirer
    ports:
      - "5000:5000"

volumes:
  kafka_data:
