version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "payments:1:1"
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - postgres
      - redis

  connector:
    build:
      context: ./connector
    depends_on:
      - kafka
      - postgres
      - api

  acquirer_simulator:
    build:
      context: ./acquirer_simulator
    ports:
      - "8001:8001"

volumes:
  pgdata:
